
name: ci

on:
  push:
    branches:
      - 'main'
  pull_request: {}
  # allow manual runs:
  workflow_dispatch: {}

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tillitis/tkey-builder:2
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'

      - name: checkout
        uses: actions/checkout@v3
        with:
          # fetch-depth: 0
          persist-credentials: false

      - name: Clone tkey-libs
        uses: actions/checkout@v3
        with:
          repository: tillitis/tkey-libs
          ref: v0.0.2
          path: tkey-libs

      - name: fix
        # https://github.com/actions/runner-images/issues/6775
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build tkey-libs
        run: |
          cd tkey-libs
          make

      - name: make
        run: make LIBDIR=./tkey-libs

      - name: check fmt of c code
        run: make checkfmt

      # - name: check for SPDX tags
      #   run: ./tools/spdx-ensure
